export const SEO_KEYWORDS = [
  // Primary SaaS keywords
  "SaaS solutions",
  "software as a service",
  "cloud-based SaaS",
  "SaaS startup",
  "multi-industry SaaS",
  "SaaS platform development",
  "subscription software",
  "cloud software solutions",
  "SaaS applications",
  "business SaaS tools",

  // Company branding keywords
  "eMaraNex",
  "emaraNex",
  "emara nex",
  "eMaranex",
  "emaranex",
  "emara next",
  "eMaraNex SaaS",
  "eMaraNex software",
  "eMaraNex platform",

  // Rabbit farming specific keywords
  "rabbit farming",
  "rabbit farming Kenya",
  "rabbit farming East Africa",
  "rabbits farming in Kenya",
  "rabbits in Kenya",
  "rabbit management",
  "rabbit management system",
  "rabbit breeding",
  "rabbit breeding Kenya",
  "rabbit breeding management",
  "rabbit breeding software",
  "rabbit breeding records",
  "rabbit health",
  "rabbit health management",
  "rabbit health tracking",
  "rabbit health records",
  "rabbit meat",
  "rabbit meat Kenya",
  "rabbit meat production",
  "rabbit meat farming",
  "rabbit sales",
  "rabbit sales tracking",
  "rabbit sales management",
  "rabbit sales Kenya",
  "rabbit urine",
  "rabbit urine collection",
  "rabbit manure",
  "rabbit manure management",
  "rabbit hutches",
  "rabbit hutches Kenya",
  "rabbit housing",
  "rabbit kefir",
  "rabbit kefir production",
  "commercial rabbit farming",
  "rabbit farm business",
  "rabbit farming profits",
  "rabbit farming income",

  // Farm management keywords
  "farm management",
  "farm management Kenya",
  "farm management East Africa",
  "farm management system",
  "farm management software",
  "farm management platform",
  "farming management",
  "farming management system",
  "farming systems",
  "farming systems Kenya",
  "farm record keeping",
  "farming record keeping",
  "farm records software",
  "farm data management",
  "agricultural record keeping",
  "livestock record keeping",
  "farm inventory management",
  "farm expense tracking",
  "farm income tracking",
  "farm analytics",
  "farm reporting",
  "digital farming",
  "smart farming",
  "precision farming",
  "farm automation",

  // Industry-specific SaaS keywords
  "farm management SaaS",
  "livestock management SaaS",
  "rabbit breeding SaaS",
  "agricultural SaaS platform",
  "farming SaaS Kenya",
  "livestock SaaS Kenya",
  "SME business SaaS",
  "healthcare management SaaS",
  "inventory management SaaS",
  "expense tracking SaaS",
  "earnings tracking SaaS",
  "cosmetics business SaaS",
  "retail management SaaS",
  "financial tracking SaaS",

  // Feature-specific keywords
  "record keeping software",
  "breeding management system",
  "cost tracking software",
  "business analytics SaaS",
  "automated alerts SaaS",
  "backup solutions SaaS",
  "notification systems SaaS",
  "reporting dashboard SaaS",
  "multi-tenant SaaS",
  "scalable SaaS architecture",

  // Location-based keywords
  "Kenya farm management",
  "East Africa farming software",
  "African agriculture technology",
  "Kenya livestock management",
  "East Africa rabbit farming",
  "Kenya agricultural software",
  "African farming solutions",
]

export const STRUCTURED_DATA = {
  "@context": "https://schema.org",
  "@type": "SoftwareApplication",
  name: "eMaraNex - Multi-Industry SaaS Solutions",
  applicationCategory: "BusinessApplication",
  operatingSystem: "Web, iOS, Android",
  description:
    "SaaS startup building industry-specific software solutions including farm management, SME business tools, healthcare systems, and inventory management platforms.",
  offers: {
    "@type": "Offer",
    price: "29",
    priceCurrency: "USD",
    availability: "https://schema.org/InStock",
  },
  aggregateRating: {
    "@type": "AggregateRating",
    ratingValue: "4.9",
    ratingCount: "2547",
  },
  author: {
    "@type": "Organization",
    name: "eMaraNex",
    url: "https://emaranex.com",
    sameAs: [
      "https://twitter.com/emaranex",
      "https://facebook.com/emaranex",
      "https://linkedin.com/company/emaranex"
    ],
    address: {
      "@type": "PostalAddress",
      addressCountry: "Kenya",
      addressRegion: "East Africa"
    }
  },
  category: "Agriculture Technology",
  keywords: "rabbit farming, farm management, livestock tracking, breeding records, Kenya agriculture, East Africa farming",
  applicationSubCategory: "Farm Management Software",
  featureList: [
    "Rabbit breeding management",
    "Livestock health tracking",
    "Farm record keeping",
    "Sales and inventory management",
    "Automated alerts and notifications",
    "Financial tracking and reporting"
  ]
}